#pragma once

#include "driver/gpio.h"
#include "driver/i2s_std.h"

// Override these from the build system or a future Kconfig file to keep
// deployment secrets and board-specific values out of source control.
#ifndef DEMO_WIFI_SSID
#define DEMO_WIFI_SSID           ""
#endif

#ifndef DEMO_WIFI_PASSWORD
#define DEMO_WIFI_PASSWORD       ""
#endif

#ifndef DEMO_WIFI_CONNECT_TIMEOUT_MS
#define DEMO_WIFI_CONNECT_TIMEOUT_MS 15000
#endif

#ifndef DEMO_WIFI_MAXIMUM_RETRY
#define DEMO_WIFI_MAXIMUM_RETRY 5
#endif

#ifndef DEMO_WIFI_POWER_SAVE_NONE
#define DEMO_WIFI_POWER_SAVE_NONE 1
#endif

#ifndef DEMO_SERVER_BASE_URL
#define DEMO_SERVER_BASE_URL     ""
#endif

#ifndef DEMO_CLOUD_SUBMIT_TIMEOUT_MS
#define DEMO_CLOUD_SUBMIT_TIMEOUT_MS 10000
#endif

#ifndef DEMO_CLOUD_POLL_TIMEOUT_MS
#define DEMO_CLOUD_POLL_TIMEOUT_MS 30000
#endif

#ifndef DEMO_CLOUD_POLL_REQUEST_TIMEOUT_MS
#define DEMO_CLOUD_POLL_REQUEST_TIMEOUT_MS 10000
#endif

#ifndef DEMO_CLOUD_POLL_INTERVAL_MS
#define DEMO_CLOUD_POLL_INTERVAL_MS 1000
#endif

#define DEMO_AUDIO_MODE_V2_ASYNC 1
#define DEMO_AUDIO_MODE_V3_REALTIME 2

#ifndef DEMO_AUDIO_MODE
#define DEMO_AUDIO_MODE DEMO_AUDIO_MODE_V2_ASYNC
#endif

#ifndef DEMO_REALTIME_SESSION_TIMEOUT_MS
#define DEMO_REALTIME_SESSION_TIMEOUT_MS 10000
#endif

#ifndef DEMO_REALTIME_AUDIO_OPEN_TIMEOUT_MS
#define DEMO_REALTIME_AUDIO_OPEN_TIMEOUT_MS 10000
#endif

#ifndef DEMO_REALTIME_AUDIO_READ_TIMEOUT_MS
#define DEMO_REALTIME_AUDIO_READ_TIMEOUT_MS 8000
#endif

#ifndef DEMO_AUDIO_DOWNLOAD_TIMEOUT_MS
#define DEMO_AUDIO_DOWNLOAD_TIMEOUT_MS 15000
#endif

#ifndef DEMO_WAV_DOWNLOAD_INITIAL_BYTES
#define DEMO_WAV_DOWNLOAD_INITIAL_BYTES 4096
#endif

#ifndef DEMO_WAV_DOWNLOAD_MAX_BYTES
#define DEMO_WAV_DOWNLOAD_MAX_BYTES (1024 * 1024)
#endif

#ifndef DEMO_AUDIO_PLAY_CHUNK_BYTES
#define DEMO_AUDIO_PLAY_CHUNK_BYTES 1024
#endif

#ifndef DEMO_AUDIO_PLAY_WRITE_TIMEOUT_MS
#define DEMO_AUDIO_PLAY_WRITE_TIMEOUT_MS 1000
#endif

#ifndef DEMO_REALTIME_AUDIO_JITTER_BUFFER_BYTES
#define DEMO_REALTIME_AUDIO_JITTER_BUFFER_BYTES 65536
#endif

#ifndef DEMO_REALTIME_AUDIO_JITTER_PREBUFFER_BYTES
#define DEMO_REALTIME_AUDIO_JITTER_PREBUFFER_BYTES 40960
#endif

#ifndef DEMO_REALTIME_AUDIO_JITTER_READ_BYTES
#define DEMO_REALTIME_AUDIO_JITTER_READ_BYTES 1024
#endif

#ifndef DEMO_REALTIME_AUDIO_ENQUEUE_WARN_MS
#define DEMO_REALTIME_AUDIO_ENQUEUE_WARN_MS 50
#endif

#ifndef DEMO_REALTIME_AUDIO_CLOSE_WAIT_LOG_MS
#define DEMO_REALTIME_AUDIO_CLOSE_WAIT_LOG_MS 1000
#endif

#ifndef DEMO_REALTIME_AUDIO_CLOSE_WAIT_TIMEOUT_MS
#define DEMO_REALTIME_AUDIO_CLOSE_WAIT_TIMEOUT_MS 5000
#endif

#ifndef DEMO_REALTIME_AUDIO_CLOSE_TAIL_TOLERANCE_BYTES
#define DEMO_REALTIME_AUDIO_CLOSE_TAIL_TOLERANCE_BYTES DEMO_REALTIME_AUDIO_JITTER_READ_BYTES
#endif

#ifndef DEMO_REALTIME_AUDIO_ACCEPT_FORMATS
#define DEMO_REALTIME_AUDIO_ACCEPT_FORMATS "opus,pcm"
#endif

#ifndef DEMO_REALTIME_AUDIO_HTTP_READ_CHUNK_BYTES
#define DEMO_REALTIME_AUDIO_HTTP_READ_CHUNK_BYTES 4096
#endif

#ifndef DEMO_REALTIME_AUDIO_ENCODED_QUEUE_LENGTH
#define DEMO_REALTIME_AUDIO_ENCODED_QUEUE_LENGTH 48
#endif

#ifndef DEMO_REALTIME_AUDIO_PCM_QUEUE_LENGTH
#define DEMO_REALTIME_AUDIO_PCM_QUEUE_LENGTH 36
#endif

#ifndef DEMO_REALTIME_AUDIO_DECODE_TASK_STACK_SIZE
#define DEMO_REALTIME_AUDIO_DECODE_TASK_STACK_SIZE 24576
#endif

#ifndef DEMO_REALTIME_AUDIO_PLAYBACK_TASK_STACK_SIZE
#define DEMO_REALTIME_AUDIO_PLAYBACK_TASK_STACK_SIZE 4096
#endif

#ifndef DEMO_REALTIME_AUDIO_QUEUE_SEND_TIMEOUT_MS
#define DEMO_REALTIME_AUDIO_QUEUE_SEND_TIMEOUT_MS 800
#endif

#ifndef DEMO_REALTIME_AUDIO_TASK_JOIN_TIMEOUT_MS
#define DEMO_REALTIME_AUDIO_TASK_JOIN_TIMEOUT_MS 20000
#endif

#ifndef DEMO_REALTIME_INTRO_ENABLED
#define DEMO_REALTIME_INTRO_ENABLED 0
#endif

#ifndef DEMO_REALTIME_INTRO_PATH
#define DEMO_REALTIME_INTRO_PATH "/spiffs/intro_1.pcm"
#endif

#ifndef DEMO_REALTIME_INTRO_MAX_BYTES
#define DEMO_REALTIME_INTRO_MAX_BYTES (64 * 1024)
#endif

#ifndef DEMO_RECORD_PROMPT_ENABLED
#define DEMO_RECORD_PROMPT_ENABLED 0
#endif

#ifndef DEMO_RECORD_PROMPT_PATH
#define DEMO_RECORD_PROMPT_PATH "/spiffs/record_prompt_1.pcm"
#endif

#ifndef DEMO_RECORD_PROMPT_MAX_BYTES
#define DEMO_RECORD_PROMPT_MAX_BYTES (64 * 1024)
#endif

#ifndef DEMO_SPIFFS_BASE_PATH
#define DEMO_SPIFFS_BASE_PATH "/spiffs"
#endif

#ifndef DEMO_SPIFFS_PARTITION_LABEL
#define DEMO_SPIFFS_PARTITION_LABEL "storage"
#endif

#ifndef DEMO_SPIFFS_MAX_FILES
#define DEMO_SPIFFS_MAX_FILES 4
#endif

#ifndef DEMO_AUDIO_INPUT_GAIN_DB
#define DEMO_AUDIO_INPUT_GAIN_DB 42.0f
#endif

#ifndef DEMO_AUDIO_OUTPUT_VOLUME
#define DEMO_AUDIO_OUTPUT_VOLUME 100
#endif

#ifndef DEMO_DEVICE_ID
#define DEMO_DEVICE_ID           ""
#endif

// Board and trigger selection.
#define DEMO_BOARD_PROFILE_LEGACY_REFERENCE 0
#define DEMO_BOARD_PROFILE_ESP_VOCAT_V1_2 1

#ifndef DEMO_BOARD_PROFILE
#define DEMO_BOARD_PROFILE DEMO_BOARD_PROFILE_ESP_VOCAT_V1_2
#endif

#define DEMO_TRIGGER_SOURCE_BUTTON   1
#define DEMO_TRIGGER_SOURCE_TOUCH    2
#define DEMO_TRIGGER_SOURCE_WAKE_WORD 3

#ifndef DEMO_TRIGGER_SOURCE
#if DEMO_BOARD_PROFILE == DEMO_BOARD_PROFILE_LEGACY_REFERENCE
#define DEMO_TRIGGER_SOURCE DEMO_TRIGGER_SOURCE_BUTTON
#else
#define DEMO_TRIGGER_SOURCE DEMO_TRIGGER_SOURCE_BUTTON
#endif
#endif

#if DEMO_BOARD_PROFILE == DEMO_BOARD_PROFILE_ESP_VOCAT_V1_2
#define DEMO_BOARD_NAME "ESP-VoCat"
#define DEMO_BOARD_REVISION "v1.2"
#else
#define DEMO_BOARD_NAME "ESP32-S3 Reference"
#define DEMO_BOARD_REVISION "legacy"
#endif

// Default wake input is a dedicated GPIO line. For the current hardware,
// the line is active-low and held high with the internal pull-up.
#define DEMO_BUTTON_GPIO         GPIO_NUM_6
#ifndef DEMO_BUTTON_ACTIVE_LEVEL
#define DEMO_BUTTON_ACTIVE_LEVEL  0
#endif

#ifndef DEMO_BUTTON_PULL_UP_ENABLE
#define DEMO_BUTTON_PULL_UP_ENABLE 1
#endif

#ifndef DEMO_BUTTON_PULL_DOWN_ENABLE
#define DEMO_BUTTON_PULL_DOWN_ENABLE 0
#endif

#ifndef DEMO_BUTTON_DEBOUNCE_MS
#define DEMO_BUTTON_DEBOUNCE_MS   20
#endif

#ifndef DEMO_TRIGGER_POLL_INTERVAL_MS
#define DEMO_TRIGGER_POLL_INTERVAL_MS 20
#endif

#ifndef DEMO_PIPELINE_TASK_STACK_SIZE
#define DEMO_PIPELINE_TASK_STACK_SIZE 24576
#endif

#ifndef DEMO_PIPELINE_TASK_PRIORITY
#define DEMO_PIPELINE_TASK_PRIORITY 5
#endif

#define DEMO_I2S_MIC_BCLK_GPIO   GPIO_NUM_4
#define DEMO_I2S_MIC_WS_GPIO     GPIO_NUM_5
#define DEMO_I2S_MIC_SD_GPIO     GPIO_NUM_6
#ifndef DEMO_I2S_MIC_PORT
#define DEMO_I2S_MIC_PORT        I2S_NUM_0
#endif
#ifndef DEMO_I2S_MIC_SLOT_BITS
#define DEMO_I2S_MIC_SLOT_BITS   32
#endif
#ifndef DEMO_I2S_MIC_SLOT_MASK
#define DEMO_I2S_MIC_SLOT_MASK   I2S_STD_SLOT_LEFT
#endif
#ifndef DEMO_I2S_MIC_READ_TIMEOUT_MS
#define DEMO_I2S_MIC_READ_TIMEOUT_MS 100
#endif
#ifndef DEMO_I2S_MIC_ZERO_READ_LIMIT
#define DEMO_I2S_MIC_ZERO_READ_LIMIT 3
#endif
#define DEMO_I2S_SPK_BCLK_GPIO   GPIO_NUM_7
#define DEMO_I2S_SPK_WS_GPIO     GPIO_NUM_8
#define DEMO_I2S_SPK_SD_GPIO     GPIO_NUM_9
#ifndef DEMO_I2S_SPK_PORT
#define DEMO_I2S_SPK_PORT        I2S_NUM_1
#endif
#ifndef DEMO_I2S_SPK_SLOT_MASK
#define DEMO_I2S_SPK_SLOT_MASK   I2S_STD_SLOT_LEFT
#endif

// Audio format.
#define DEMO_AUDIO_SAMPLE_RATE    16000
#define DEMO_AUDIO_BITS_PER_SAMPLE 16
#define DEMO_AUDIO_CHANNELS       1
#define DEMO_AUDIO_BYTES_PER_SAMPLE (DEMO_AUDIO_BITS_PER_SAMPLE / 8)

// Recording and buffering.
#define DEMO_RECORD_DURATION_SEC  4
#ifndef DEMO_RECORD_VAD_ENABLED
#define DEMO_RECORD_VAD_ENABLED 1
#endif
#ifndef DEMO_WAIT_FOR_SPEECH_TIMEOUT_MS
#define DEMO_WAIT_FOR_SPEECH_TIMEOUT_MS 3000
#endif
#ifndef DEMO_WAITING_SPEECH_ARM_MS
#define DEMO_WAITING_SPEECH_ARM_MS 150
#endif
#ifndef DEMO_SPEECH_START_HOLD_MS
#define DEMO_SPEECH_START_HOLD_MS 128
#endif
#ifndef DEMO_RECORD_AFTER_SPEECH_MAX_MS
#define DEMO_RECORD_AFTER_SPEECH_MAX_MS (DEMO_RECORD_DURATION_SEC * 1000)
#endif
#ifndef DEMO_RECORD_MIN_DURATION_MS
#define DEMO_RECORD_MIN_DURATION_MS 1000
#endif
#ifndef DEMO_RECORD_VAD_SILENCE_MS
#define DEMO_RECORD_VAD_SILENCE_MS 700
#endif
#ifndef DEMO_RECORD_VAD_START_THRESHOLD
#define DEMO_RECORD_VAD_START_THRESHOLD 450
#endif
#ifndef DEMO_RECORD_VAD_SILENCE_THRESHOLD
#define DEMO_RECORD_VAD_SILENCE_THRESHOLD 300
#endif
#define DEMO_AUDIO_FRAME_BYTES    512
#define DEMO_AUDIO_CHUNK_BYTES    2048
#define DEMO_AUDIO_BUFFER_SAMPLES ((DEMO_AUDIO_SAMPLE_RATE * DEMO_RECORD_AFTER_SPEECH_MAX_MS / 1000) * DEMO_AUDIO_CHANNELS)
#define DEMO_AUDIO_BUFFER_BYTES   (DEMO_AUDIO_BUFFER_SAMPLES * DEMO_AUDIO_BYTES_PER_SAMPLE)
#define DEMO_SPEECH_START_HOLD_BYTES \
    ((DEMO_AUDIO_SAMPLE_RATE * DEMO_SPEECH_START_HOLD_MS / 1000) * DEMO_AUDIO_CHANNELS * DEMO_AUDIO_BYTES_PER_SAMPLE)
#define DEMO_RECORD_MIN_BYTES \
    ((DEMO_AUDIO_SAMPLE_RATE * DEMO_RECORD_MIN_DURATION_MS / 1000) * DEMO_AUDIO_CHANNELS * DEMO_AUDIO_BYTES_PER_SAMPLE)
#define DEMO_RECORD_VAD_SILENCE_BYTES \
    ((DEMO_AUDIO_SAMPLE_RATE * DEMO_RECORD_VAD_SILENCE_MS / 1000) * DEMO_AUDIO_CHANNELS * DEMO_AUDIO_BYTES_PER_SAMPLE)

_Static_assert(DEMO_AUDIO_BITS_PER_SAMPLE % 8 == 0,
               "DEMO_AUDIO_BITS_PER_SAMPLE must be byte-aligned");
_Static_assert(DEMO_AUDIO_BYTES_PER_SAMPLE > 0,
               "DEMO_AUDIO_BYTES_PER_SAMPLE must be non-zero");
_Static_assert(DEMO_I2S_MIC_SLOT_BITS % 8 == 0,
               "DEMO_I2S_MIC_SLOT_BITS must be byte-aligned");
_Static_assert(DEMO_I2S_MIC_SLOT_BITS == 32,
               "DEMO_I2S_MIC_SLOT_BITS must be 32 for the INMP441 capture path");
_Static_assert(DEMO_AUDIO_FRAME_BYTES % DEMO_AUDIO_BYTES_PER_SAMPLE == 0,
               "DEMO_AUDIO_FRAME_BYTES must align to sample size");
_Static_assert(DEMO_AUDIO_CHUNK_BYTES % DEMO_AUDIO_BYTES_PER_SAMPLE == 0,
               "DEMO_AUDIO_CHUNK_BYTES must align to sample size");
_Static_assert(DEMO_AUDIO_CHUNK_BYTES % (DEMO_I2S_MIC_SLOT_BITS / 8) == 0,
               "DEMO_AUDIO_CHUNK_BYTES must align to I2S slot size");
_Static_assert(DEMO_RECORD_MIN_BYTES <= DEMO_AUDIO_BUFFER_BYTES,
               "DEMO_RECORD_MIN_DURATION_MS must fit the recording buffer");
_Static_assert(DEMO_RECORD_VAD_SILENCE_BYTES > 0,
               "DEMO_RECORD_VAD_SILENCE_MS must be positive");
_Static_assert(DEMO_SPEECH_START_HOLD_BYTES > 0,
               "DEMO_SPEECH_START_HOLD_MS must be positive");
_Static_assert(DEMO_AUDIO_PLAY_CHUNK_BYTES % DEMO_AUDIO_BYTES_PER_SAMPLE == 0,
               "DEMO_AUDIO_PLAY_CHUNK_BYTES must align to sample size");
_Static_assert(DEMO_REALTIME_AUDIO_JITTER_BUFFER_BYTES >= DEMO_REALTIME_AUDIO_JITTER_READ_BYTES,
               "DEMO_REALTIME_AUDIO_JITTER_BUFFER_BYTES must fit one read chunk");
_Static_assert(DEMO_REALTIME_AUDIO_JITTER_PREBUFFER_BYTES <= DEMO_REALTIME_AUDIO_JITTER_BUFFER_BYTES,
               "DEMO_REALTIME_AUDIO_JITTER_PREBUFFER_BYTES must fit the jitter buffer");
_Static_assert(DEMO_REALTIME_AUDIO_JITTER_READ_BYTES % DEMO_AUDIO_BYTES_PER_SAMPLE == 0,
               "DEMO_REALTIME_AUDIO_JITTER_READ_BYTES must align to sample size");
_Static_assert(DEMO_TRIGGER_SOURCE == DEMO_TRIGGER_SOURCE_BUTTON ||
                   DEMO_TRIGGER_SOURCE == DEMO_TRIGGER_SOURCE_TOUCH ||
                   DEMO_TRIGGER_SOURCE == DEMO_TRIGGER_SOURCE_WAKE_WORD,
               "DEMO_TRIGGER_SOURCE must be button, touch, or wake-word");
_Static_assert(DEMO_AUDIO_MODE == DEMO_AUDIO_MODE_V2_ASYNC ||
                   DEMO_AUDIO_MODE == DEMO_AUDIO_MODE_V3_REALTIME,
               "DEMO_AUDIO_MODE must be v2_async or v3_realtime");
